GET http://localhost:3001/api/persons


###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "na",
    "number": "12345"
}

###
GET http://localhost:3001/info


###
PUT http://localhost:3001/api/persons/63c830aef81ccaf37ce488a6 HTTP/1.1
content-type: application/json

{
    "name": "na",
    "number": "111111111"
}

###
GET http://localhost:3001/api/persons/4


###
GET http://localhost:3001/info




###
GET http://localhost:3001/api/persons/7



###
DELETE http://localhost:3001/api/persons/4



###
GET https://restless-butterfly-3150.fly.dev/api/persons


###
POST https://restless-butterfly-3150.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "assjjdasdsa",
    "number": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###
PUT https://restless-butterfly-3150.fly.dev/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "assjjdasdsa",
    "number": "111111111"
}

